# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    git clone https://github.com/advantecher/nfclib.git test
    cd test
    git remote add --mirror=fetch secondary https://wise-deviceon@dev.azure.com/wise-deviceon/ePaper%20Core/_git/App%20-%20NFC%20Sample%20App%20%28Android%29
    git config --global user.email "fabian.chung@advantech.com"
    git config --global user.name "Fabian Chung"
    git fetch origin
    git push secondary --all
  displayName: 'Push to Azure Repos'
